fixtures:
  symlinks:
    iis: "#{source_dir}"
  repositories:
    dsc:
      repo: "https://github.com/puppetlabs/puppetlabs-dsc.git"
    acl:
      repo: "https://github.com/puppetlabs/puppetlabs-acl.git"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
